#ifndef TERMINAL_COLORS_H
#define TERMINAL_COLORS_H

#define TERMINAL_COLOR_RESET        "\x1b[0m"
#define TERMINAL_COLOR_RED          "\x1b[31m"
#define TERMINAL_COLOR_ORANGE       "\033[38;5;208m"
#define TERMINAL_COLOR_GREEN        "\x1b[32m"
#define TERMINAL_COLOR_YELLOW       "\x1b[33m"
#define TERMINAL_COLOR_BLUE         "\x1b[34m"
#define TERMINAL_COLOR_MAGENTA      "\x1b[35m"
#define TERMINAL_COLOR_CYAN         "\x1b[36m"
#define TERMINAL_COLOR_GRAY         "\x1b[90m"
#define TERMINAL_COLOR_BOLD         "\x1b[1m"
#define TERMINAL_COLOR_DIM          "\x1b[2m"
#define TERMINAL_COLOR_ITALIC       "\x1b[3m"
#define TERMINAL_COLOR_UNDERLINE    "\x1b[4m"
#define TERMINAL_COLOR_BLINK        "\x1b[5m"
#define TERMINAL_COLOR_REVERSE      "\x1b[6m"

#define TERMINAL_BOLD_YELLOW        TERMINAL_COLOR_BOLD TERMINAL_COLOR_YELLOW
#define TERMINAL_BOLD_RED        TERMINAL_COLOR_BOLD TERMINAL_COLOR_RED
#define TERMINAL_BOLD_GREEN        TERMINAL_COLOR_BOLD TERMINAL_COLOR_GREEN
#define TERMINAL_BOLD_BLUE        TERMINAL_COLOR_BOLD TERMINAL_COLOR_BLUE
#define TERMINAL_BOLD_GRAY        TERMINAL_COLOR_BOLD TERMINAL_COLOR_GRAY




#endif